### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by Rameron** [Rinnegatamante/vitaRTCW#6]
Hello!

I installed vitaSDK, vitaGL and tried to compile vitaRTCW but received some errors. Can someone tell me what's wrong?
![image](https://user-images.githubusercontent.com/35733343/106369237-550b2e00-6358-11eb-9c3d-63c036bd2aee.png)

**Comment by Rinnegatamante** [comment]
That's probably caused by recent additions to newlib. You can very likely remove all the redifinitions safely.

**Comment by Rameron** [comment]
> That's probably caused by recent additions to newlib. You can very likely remove all the redifinitions safely.

Ok, I'll try, thanks.

**Comment by Rameron** [comment]
There appear another problem. It was "vglStartRendering" and "vglStopRendering" declarations in "VitaGL.h", but it's removed in the master branch now. So file "/vitaRTCW/mp_code/psp2/psp2_glimp.c" don't wanna to compile. Should I use another branch of VitaGL or something? Thanks.

```
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/10.1.0/../../../../arm-vita-eabi/bin/ld: mp_code/psp2/psp2_glimp.o: in function `GLimp_Init':
/home/rameron/vitaRTCW/mp_code/psp2/psp2_glimp.c:130: undefined reference to `vglStartRendering'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/10.1.0/../../../../arm-vita-eabi/bin/ld: mp_code/psp2/psp2_glimp.o: in function `GLimp_EndFrame':
/home/rameron/vitaRTCW/mp_code/psp2/psp2_glimp.c:167: undefined reference to `vglStopRendering'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/10.1.0/../../../../arm-vita-eabi/bin/ld: /home/rameron/vitaRTCW/mp_code/psp2/psp2_glimp.c:168: undefined reference to `vglStartRendering'
```

**Comment by Rinnegatamante** [comment]
That's caused by new vitaGL having changed some API funcs. I'll submit a commit to fix that in the near future but in the meantime, you can look at this and implement same changes in vitaRTCW: https://github.com/Rinnegatamante/vitaQuakeIII/commit/9159a9e094794dc6ec915abf287cb56a7fcdf74f

**Comment by Rameron** [comment]
Anyway, there occurs an error`collect2: error: ld returned 1 exit status`. I already understand it was a bad idea to try to compile by myself. So it'll be better to wait for the new vpk and don't ask for dummy questions.
