### ISSUE TITLE
Build fails with recent PSVita toolchain

### ISSUE THREAD

**Issue by danielt3** [Rinnegatamante/vitaRTCW#7]
I tried to build the lastest code using the current PSVita toolchain and the build breaks because it can't find the `sceDmacMemcpy` symbol. The build log line that actually matters is:
```
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/10.3.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/10.3.0/../../../../arm-vita-eabi/lib/libvitaGL.a(mem_utils.o): in function `vgl_memcpy':
(.text+0x496): undefined reference to `sceDmacMemcpy'
```

I'm on Debian Linux 10 ("buster").

Could you please help me fix this one?

**Comment by Rinnegatamante** [comment]
You're not on latest commit (aka you're not linking SceKernelDmacMgr_stub)

**Comment by danielt3** [comment]
I'm on last commit (d993249a8d057266713b308713072b589296c3c2).

Actually `Makefile.mp` wasn't linking with `SceKernelDmacMgr_stub` and the build failed since it gets called earlier and just calling `make` makes it use the first target it finds (`release` in this case).

The `release` target actually calls the `Makefile.mp` first which didn't link with `SceKernelDmacMgr_stub`.

I'm creating a PR to fix this.

Thank you.

**Comment by danielt3** [comment]
Fix: https://github.com/Rinnegatamante/vitaRTCW/pull/8
